services:
  backend:
    image: php:8.2-apache
    container_name: backend-dev
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=films
      - DB_USER=root
      - DB_PASS=root
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0.35-debian
    container_name: db-dev
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=films
    ports:
      - "3306:3306"
    volumes:
      - db_data_dev:/var/lib/mysql
      - ./films_dump.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data_dev:
